# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180326_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='map',
            field=models.CharField(max_length=255, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0434\u043b\u044f \u043a\u0430\u0440\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='type',
            field=models.IntegerField(choices=[(0, '\u0423\u0417\u0418'), (1, '\u0424\u0443\u043d\u043a\u0446\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u0430\u044f \u0434\u0438\u0430\u0433\u043d\u043e\u0441\u0442\u0438\u043a\u0430'), (2, '\u041a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f \u0432\u0440\u0430\u0447\u0430 \u043a\u0430\u0440\u0434\u0438\u043e\u043b\u043e\u0433\u0430')], default=0, verbose_name='\u0422\u0438\u043f'),
        ),
    ]
