# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180901_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='price',
            name='ordering',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
